name: First action

on:
    workflow_dispatch:
        inputs:
            input-one:
                description: 'This is the first input to the workflow'
                required: true
                default: 'one'
                type: string
            
            input-two:
                description: 'This is the second input to the workflow'
                required: false
                type: string

            skip-step:
                description: 'Skip step if true'
                default: false
                type: boolean

    
    push:
        branches:
            - main

    pull_request:
        types:
            - opened
            - reopened
            - closed

        branches:
            - main
    

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print input one
              run: echo ${{ inputs.input-one }}
            
            - run: echo "This is a step without a name"
    
    job2:
        if: ${{ inputs.skip-step }}
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "This is step 1"
