name: First action

on:
    workflow_dispatch:
    
    push:
        branches:
            - main

    pull_request:
        types:
            - opened
            - reopened

        branches:
            - main
    

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: step with name
              run: echo "This is a step with a name"
            
            - run: echo "This is a step without a name"
    
    job2:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "This is step 1"
